name: Trigger Run Tests Workflow

on:
  # Manual trigger from GitHub UI
  workflow_dispatch:
  repository_dispatch:


jobs:
  trigger:
    runs-on: ubuntu-latest
    
    if: >
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'repository_dispatch' && github.event.action == 'deployment.succeeded')

    steps:
      - name: Log Webhook Payload
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event action: ${{ github.event.action }}"
          echo "Full JSON payload:"
          echo "${{ toJSON(github.event) }}"

      - name: Trigger Visual Tests
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'dydxopsdao',
              repo: 'E2E',
              workflow_id: 'run-tests.yml',
              ref: 'main'
            });
