name: Trigger Run Tests Workflow

on:
  # Manual trigger from GitHub UI
  workflow_dispatch:
  repository_dispatch:
    types: [deployment]

jobs:
  trigger:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Always Run Debug
        if: always()
        run: |
          echo "============ Debug Info ============"
          echo "Event name: ${{ github.event_name }}"
          echo "Event type: ${{ github.event.event_type }}"
          echo "Repository dispatch type: ${{ github.event.action }}"
          echo "Client payload: ${{ toJSON(github.event.client_payload) }}"
          echo "Full event: ${{ toJSON(github.event) }}"
          echo "Job status: ${{ job.status }}"
          echo "====================================="

      - name: Trigger Visual Tests
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'dydxopsdao',
              repo: 'E2E',
              workflow_id: 'run-tests.yml',
              ref: 'main'
            });
