name: Trigger Run Tests Workflow

on:
  repository_dispatch:
    types: [vercel-deploy]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger run-tests.yml
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Content-Type: application/json" \
            --data '{"ref":"main"}' \
            https://api.github.com/repos/dydxopsdao/E2E/actions/workflows/run-tests.yml/dispatches
