name: Trigger Run Tests Workflow

on:
  repository_dispatch:
    types: [deployment]

jobs:
  trigger:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Always Run Debug
        if: always()
        run: |
          echo "============ Debug Info ============"
          echo "Deployment ID: ${{ github.event.client_payload.payload.deploymentId }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Full event: ${{ toJSON(github.event) }}"
          echo "====================================="

      - name: Trigger Visual Tests
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const deploymentId = context.payload.client_payload?.payload?.deploymentId || 'manual';
            console.log('Debug - Deployment ID:', deploymentId);
            console.log('Debug - Full context:', JSON.stringify(context.payload));
            
            await github.rest.actions.createWorkflowDispatch({
              owner: 'dydxopsdao',
              repo: 'E2E',
              workflow_id: 'run-tests.yml',
              ref: 'main',
              inputs: {
                deployment_id: deploymentId
              }
            });
